### ISSUE TITLE
Shorten trees consisting only of “These two derivations have already been compared” as the leafs.

### ISSUE THREAD

**Issue by Ekleog** [Gabriella439/nix-diff#8]
Applying https://github.com/Gabriel439/nix-diff/pull/7 is great in that it allows to not miss a change when upgrading a system (basically, the idea there is to be able to run a cron that nixos-rebuild --upgrade and sends the nix-diff by email to know when to upgrade).

However, it means there can quickly be a lot of cruft: last release-18.03 bump included an upgrade to openssl and bash… and this means the tree is full of “These two derivations have already been compared”. Actually, that's 3.2MiB of “These two derivations have already been compared” with this update. (also, I don't think that's exclusive to having #7 applied, and I guess that could happen with current nix-diff too, I just happen to have written #7 to work around the fact that the linux kernel upgrade blocked me from seeing anything else, and it turns out there was a curl update too)

So, I think having a flag available to shorten such trees to eg. “Skipping as only already-compared derivations have changed below” would be great.

What do you think about it?

**Comment by Gabriel439** [comment]
Yeah, I think that's a good idea.  It might even be good to make it the default behavior since those "already compared lines" seem like they don't add much in the common use case

**Comment by grahamc** [comment]
This sounds nice. I found this issue looking for a way to have nix-diff only show "interesting" differences, with a goal of putting the "interesting" changes in to a view for an automatic NixOS update prompt.

**Comment by Player-205** [comment]
Done by https://github.com/Gabriella439/nix-diff/pull/69
